# Generated by Django 5.1.15 on 2026-09-07 05:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0002_student_parents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Subject name (e.g. Mathematics)', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed homework instructions or exercise numbers')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('attachment', models.FileField(blank=True, help_text='Optional PDF or image attachment', null=True, upload_to='homework_attachments/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Teacher who assigned this homework', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_homeworks', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(help_text='Target class and section', on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='students.class')),
                ('school', models.ForeignKey(help_text='School this homework belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='schools.school')),
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homeworks',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
    ]
