# Generated by Django 5.1.15 on 2026-09-08 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
        ('schools', '0001_initial'),
        ('students', '0002_student_parents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['school', 'classroom'], name='homework_ho_school__13b73f_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['school', 'due_date'], name='homework_ho_school__f4a3b3_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['school', 'assigned_date'], name='homework_ho_school__18b9fb_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['school', 'subject'], name='homework_ho_school__426a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['school', 'is_active'], name='homework_ho_school__4d22ef_idx'),
        ),
    ]
