# Generated by Django 5.1.15 on 2026-09-09 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_homework_homework_ho_school__13b73f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
