# Generated by Django 5.1.15 on 2026-09-10 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_alter_homework_assigned_date'),
        ('schools', '0001_initial'),
        ('students', '0004_populate_existing_student_enrollments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Optional: specific student if homework is assigned individually', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_homeworks', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['school', 'student'], name='homework_ho_school__28130d_idx'),
        ),
    ]
