# Generated by Django 5.1.15 on 2026-09-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_homework_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='due_time',
            field=models.TimeField(blank=True, help_text='Optional deadline time on the due date, e.g. 16:00. Left blank the homework is simply due that day.', null=True),
        ),
    ]
