# Generated by Django 5.1.15 on 2026-09-14 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0004_populate_existing_student_enrollments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=10)),
                ('note', models.CharField(blank=True, help_text="Optional reason, e.g. 'fever' or 'family function'", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(help_text='Class the student was in on this date', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.class')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'verbose_name': 'Attendance record',
                'verbose_name_plural': 'Attendance records',
                'ordering': ['-date', 'student__admission_number'],
                'indexes': [models.Index(fields=['school', 'date'], name='attendance__school__66644e_idx'), models.Index(fields=['classroom', 'date'], name='attendance__classro_9ff4f2_idx'), models.Index(fields=['student', 'date'], name='attendance__student_76a8d7_idx'), models.Index(fields=['school', 'status'], name='attendance__school__1a7425_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='unique_attendance_per_student_per_day')],
            },
        ),
    ]
