# Generated by Django 5.1.15 on 2026-09-10 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0002_announcement_announcemen_school__5a22c8_idx_and_more'),
        ('homework', '0004_homework_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('HOMEWORK', 'Homework'), ('ANNOUNCEMENT', 'Announcement')], help_text='Type of event that generated the notification', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(blank=True, help_text='Associated announcement circular (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='announcements.announcement')),
                ('homework', models.ForeignKey(blank=True, help_text='Associated homework object (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='homework.homework')),
                ('recipient', models.ForeignKey(help_text='User who received this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
