# Generated by Django 5.1.15 on 2026-09-14 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_announcemen_school__5a22c8_idx_and_more'),
        ('attendance', '0001_initial'),
        ('homework', '0005_homework_due_time'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='attendance',
            field=models.ForeignKey(blank=True, help_text='Associated attendance record (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='attendance.attendance'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('HOMEWORK', 'Homework'), ('ANNOUNCEMENT', 'Announcement'), ('ATTENDANCE', 'Attendance')], help_text='Type of event that generated the notification', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'notification_type', '-created_at'], name='notificatio_recipie_7b2be0_idx'),
        ),
    ]
