# Generated by Django 5.1.15 on 2026-09-14 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('notifications', '0003_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='exam',
            field=models.ForeignKey(blank=True, help_text='Exam whose results this notification announces (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('HOMEWORK', 'Homework'), ('ANNOUNCEMENT', 'Announcement'), ('ATTENDANCE', 'Attendance'), ('RESULT', 'Exam result')], help_text='Type of event that generated the notification', max_length=20),
        ),
    ]
