# Generated by Django 5.1.15 on 2026-09-15 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_exam_and_more'),
        ('students', '0005_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='student',
            field=models.ForeignKey(blank=True, help_text='The child this is about, for per-child events (attendance, a result, homework set for one student). Empty for class-wide and school-wide events, which concern every child they reach.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='students.student'),
        ),
    ]
