# Generated by Django 5.1.15 on 2026-09-15 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('notifications', '0005_notification_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='conversation',
            field=models.ForeignKey(blank=True, help_text='Conversation with a new message (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='messaging.conversation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('HOMEWORK', 'Homework'), ('ANNOUNCEMENT', 'Announcement'), ('ATTENDANCE', 'Attendance'), ('RESULT', 'Exam result'), ('MESSAGE', 'Message')], help_text='Type of event that generated the notification', max_length=20),
        ),
    ]
