# Generated by Django 5.1.15 on 2026-09-14 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0004_populate_existing_student_enrollments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Mathematics', max_length=80)),
                ('code', models.CharField(blank=True, help_text='Optional short code used on timetables, e.g. MATH', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('period', models.PositiveSmallIntegerField(help_text='Period number, starting at 1')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='students.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='schools.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='timetable.subject')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timetable slot',
                'verbose_name_plural': 'Timetable slots',
                'ordering': ['weekday', 'period'],
            },
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school', 'is_active'], name='timetable_s_school__799ce6_idx'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_subject_name_per_school'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['school', 'weekday'], name='timetable_t_school__56c085_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['classroom', 'weekday'], name='timetable_t_classro_c420d2_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['teacher', 'weekday'], name='timetable_t_teacher_52a803_idx'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(fields=('classroom', 'weekday', 'period'), name='unique_period_per_class'),
        ),
    ]
