# Generated by Django 5.1.15 on 2026-09-14 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0005_class_teacher'),
        ('timetable', '0002_seed_subjects_from_homework'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Quarterly Exam', max_length=120)),
                ('academic_year', models.CharField(help_text='e.g. 2026-2027', max_length=9)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Parents see marks, totals and ranks only once this is on.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='schools.school')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.PositiveSmallIntegerField(default=100)),
                ('pass_marks', models.PositiveSmallIntegerField(default=35)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='students.class')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='exams.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_papers', to='timetable.subject')),
            ],
            options={
                'ordering': ['exam_date', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=1, help_text='Empty when the student was absent.', max_digits=5, null=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_entered', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='exams.exampaper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student')),
            ],
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['school', 'academic_year'], name='exams_exam_school__2c2b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['school', 'is_published'], name='exams_exam_school__e1672b_idx'),
        ),
        migrations.AddIndex(
            model_name='exampaper',
            index=models.Index(fields=['exam', 'classroom'], name='exams_examp_exam_id_3cf67f_idx'),
        ),
        migrations.AddConstraint(
            model_name='exampaper',
            constraint=models.UniqueConstraint(fields=('exam', 'classroom', 'subject'), name='unique_paper_per_exam_class_subject'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['student'], name='exams_mark_student_f21602_idx'),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.UniqueConstraint(fields=('paper', 'student'), name='unique_mark_per_paper_student'),
        ),
    ]
