# Generated by Django 5.1.15 on 2026-09-15 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampaper',
            name='pass_marks',
            field=models.PositiveSmallIntegerField(default=33),
        ),
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. A1', max_length=8)),
                ('min_percentage', models.DecimalField(decimal_places=2, help_text='Lowest percentage that earns this grade.', max_digits=5)),
                ('description', models.CharField(blank=True, help_text='e.g. Outstanding', max_length=60)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_bands', to='schools.school')),
            ],
            options={
                'ordering': ['-min_percentage'],
                'constraints': [models.UniqueConstraint(fields=('school', 'label'), name='unique_grade_label_per_school'), models.UniqueConstraint(fields=('school', 'min_percentage'), name='unique_grade_minimum_per_school')],
            },
        ),
    ]
