# Generated by Django 5.1.15 on 2026-09-08 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_refactor_otp_verification'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otpverification',
            new_name='accounts_ot_destina_012e93_idx',
            old_name='accounts_ot_dest_idx',
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='is_used',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact number for SMS/WhatsApp notifications', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Tenant association for strict multi-school data isolation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='schools.school'),
        ),
    ]
