# Generated by Django 5.1.15 on 2026-09-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_accounts_ot_dest_idx_accounts_ot_destina_012e93_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, help_text='User profile picture or avatar image', null=True, upload_to='profile_pictures/'),
        ),
    ]
