# Generated by Django 5.1.15 on 2026-09-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Set when the school issues a temporary password; cleared once the user picks their own.'),
        ),
        migrations.AddField(
            model_name='user',
            name='temporary_password_expires_at',
            field=models.DateTimeField(blank=True, help_text='A temporary password stops working after this moment.', null=True),
        ),
    ]
