# Generated by Django 5.1.15 on 2026-09-07 05:53

import apps.announcements.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0002_student_parents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Announcement message or circular details')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attachment', models.FileField(blank=True, help_text='Optional circular PDF or image attachment', null=True, upload_to='announcements_attachments/', validators=[apps.announcements.validators.validate_announcement_attachment])),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('IMPORTANT', 'Important'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('audience_type', models.CharField(choices=[('SCHOOL', 'School'), ('CLASS', 'Class')], default='SCHOOL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this announcement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(help_text='School this announcement belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='schools.school')),
                ('target_class', models.ForeignKey(blank=True, help_text='Target class if audience_type is CLASS', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='students.class')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
