# Generated by Django 5.1.15 on 2026-09-08 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        ('schools', '0001_initial'),
        ('students', '0002_student_parents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['school', 'published_at'], name='announcemen_school__5a22c8_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['school', 'priority'], name='announcemen_school__ee0435_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['school', 'audience_type'], name='announcemen_school__5322b2_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['school', 'is_active'], name='announcemen_school__e8a7d0_idx'),
        ),
    ]
