# Generated by Django 5.1.15 on 2026-09-07 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(blank=True, help_text='Parents or guardians linked to this student', limit_choices_to={'role': 'PARENT'}, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
