# Generated by Django 5.1.15 on 2026-09-08 05:43

import apps.students.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0002_student_parents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='Academic session in YYYY-YYYY format (e.g. 2025-2026)', max_length=20, validators=[apps.students.models.validate_academic_year_format])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True, help_text="Indicates whether this is the student's active current enrollment")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Class Enrollment',
                'verbose_name_plural': 'Student Class Enrollments',
                'ordering': ['-academic_year', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(blank=True, help_text='Teachers assigned to this class', limit_choices_to={'role': 'TEACHER'}, related_name='assigned_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class',
            name='academic_year',
            field=models.CharField(help_text='Academic session in YYYY-YYYY format (e.g. 2025-2026)', max_length=20, validators=[apps.students.models.validate_academic_year_format]),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_enrolled',
            field=models.ForeignKey(blank=True, help_text='Current active class and section of the student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.class'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['school', 'academic_year'], name='students_cl_school__7401a6_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['school', 'is_active'], name='students_cl_school__a137b4_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'is_active'], name='students_st_school__3f378d_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'class_enrolled'], name='students_st_school__ed652e_idx'),
        ),
        migrations.AddField(
            model_name='studentclassenrollment',
            name='classroom',
            field=models.ForeignKey(help_text='Class enrolled in', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.class'),
        ),
        migrations.AddField(
            model_name='studentclassenrollment',
            name='school',
            field=models.ForeignKey(help_text='School this enrollment record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='schools.school'),
        ),
        migrations.AddField(
            model_name='studentclassenrollment',
            name='student',
            field=models.ForeignKey(help_text='Enrolled student', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='studentclassenrollment',
            index=models.Index(fields=['school', 'academic_year'], name='students_st_school__e7a941_idx'),
        ),
        migrations.AddIndex(
            model_name='studentclassenrollment',
            index=models.Index(fields=['student', 'is_current'], name='students_st_student_e64435_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentclassenrollment',
            unique_together={('student', 'classroom', 'academic_year')},
        ),
    ]
